### ISSUE TITLE
Misworded comments in DataViewProvider.h

### ISSUE THREAD

**Issue by theoknock** [MrAlek/AWPagedArray#11]
The comment pertaining to the `dataObjects` array, which now reads...:

```
/**
 * The array returned will be a proxy object containing
 * NSNull values for data objects not yet loaded. As data
 * loads, the proxy updates automatically to include
 * the newly loaded objects.
 *
 * @see shouldLoadAutomatically
 */
```

...should instead read:

```
/**
* Each element in the array will contain an abstract data object (by proxy)
*  as a placeholder for the requested, concrete data object via proxy.
*  When the client requests any of the resources contained in a 
*  data object, the proxy will create a concrete instance of the
*  data object, with which the array will replace the NSNull stored in
*  the corresponding element.
*
* @see shouldLoadAutomatically
**/
```

...or, something like it, anyway. The proxy design pattern (and design patterns overall) were (and, to a large extent, still are) new to me; perfectly worded explanations are key to newbie success :)

**Comment by MrAlek** [comment]
Thanks for mentioning the somewhat confusing documentation in the demo. Although I disagree in the sense that the `DataProvider` should even less expose the complexity of the implementation using proxies.

From the consumer's point of view, it's just an array containing mixed `NSNull` and regular data values, which is expected to be automatically updated, breaking the value semantics that arrays usually possess.

I've updated the documentation to reflect this.
