### ISSUE TITLE
Usage isn't clear enough IMHO

### ISSUE THREAD

**Issue by itaispector** [MrAlek/AWPagedArray#12]
Hello, 
First of all, i appreciate all your work it's fantastic, and admire people like you who share their knowledge with the world.

I'm trying to implement your AWPagedArray, and i'm confused how to do it, since you've putted a usage example here in GitHub, but i feel it lacks a bit of information. I also downloaded the demo project, and over there i have some barriers about how to approach to it, and use it in my project.
Again i say, it could a problem for my side that i don't understand it, if you think it can be more explanatory and more easy approach, it would love that.

Thanks, and best of luck

**Comment by MrAlek** [comment]
Hi,
Thanks for the kind words :) I can understand It can be a bit daunting to implement a paging mechanism in a real-world app but it all depends on how your data fetching and presentation works. For instance if you are using `NSOperation`s, plain `NSURLSession`s, ReactiveCocoa, etc and if you are going to present the data in a table view, collection view, page view controller or some completely custom UI. The demo project is just showing one way of implementing it using operations and table views.

That considered, the promise of this library isn't really to accommodate for all of the different ways to do that but rather be a simple data structure to use in a your own solution.

I know this probably isn't the answer you are looking for but to give some guidance, the demo project works on the premise of having each view controller be given a data provider, which fetches data using operations. Those operations can for instance be wrapping `NSURLSession` tasks to fetch different pages and as they complete, they set the corresponding page in the array. While all of this happens in the background, the table view only holds a single reference to the data provider's array and uses placeholder cells whenever it encounters an `NSNull` value. As new data loads in, the table view reloads those cells to animate in real data cells. This is just one approach one can use but I hope it helps you bringing fluent pagination into your app.
