### ISSUE TITLE
Initial Page

### ISSUE THREAD

**Issue by magnett** [MrAlek/AWPagedArray#6]
Hi and thank you for all this beautiful piece of code!
It would be nice to have an option to set the initial page because right now if you set it to 0 the setObjects: forPage: method, won't register the page.

**Comment by cuongtv51** [comment]
Hi, thank for beautiful code, I agree with @magnett , i think we should have index page begin from 0, just like nature index begin from 0 in C

**Comment by MrAlek** [comment]
We could have the option to choose 0 as starting index but I'm not sure it should be the default. Other RFCs such as [RFC 5005](http://www.ietf.org/rfc/rfc5005.txt) which explains feed paging using the Atom protocol as an example, has 1-based indexing for pages.

Generally, I feel when referring to indexes. they are assumed to be 0-based but pages are assumed to be 1-based. A book or magazine or digital document doesn't start on page 0.

**Comment by magnett** [comment]
@MrAlek Just the an option to set it like "setInitialIndexNumber" would be cool!

**Comment by MrAlek** [comment]
I think I'll add it as part of immutable state in the initializer instead. Tried a naiive first implementation now but got a few test failures. Gonna try more tomorrow.

**Comment by MrAlek** [comment]
Done! Just gonna push a new podspec

**Comment by magnett** [comment]
Thanks!
