### ISSUE TITLE
What if the count can only be retrieved with a network call?

### ISSUE THREAD

**Issue by fatuhoku** [MrAlek/AWPagedArray#8]
Thanks for putting `AWPagedArray` together. It's pretty cool.  My use case is to fetch data from a Parse backend, for which I don't know the count when I present the interface.

At present `AWPagedArray` pretty much requires a fixed count to be available when the view loads, because it's a parameter of the initialiser `-initWithCount:objectsPerPage:`.

What about the cases where the count is not known until display?

**Comment by MrAlek** [comment]
Thanks for reaching out. I made `AWPagedArray` with the intention of using it for datasets with a known count.

If you don't know the count and aren't trying to pre-fill UI for cells that haven't been loaded yet, you might as well just go with a regular `NSMutableArray` and fill upp with objects as new pages load, expanding the total size each time.
